/**
 * @file cdc.h
 * @author Links (lhd@wch.cn)
 * @brief USB CDC class definition header file
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef CDC_H
#define CDC_H

/* @include */
#include "usb_define.h"

#ifdef __cplusplus
extern "C" {
#endif

/* @define */
#define CDC_LINE_STATE_DTR_MASK 0x01
#define CDC_LINE_STATE_RTS_MASK 0x02

/* @enum */
typedef enum
{
    CDC_SUBCLASS_DIRECT_LINE_CONTROL_MODEL = 0x01,
    CDC_SUBCLASS_ABSTRACT_CONTROL_MODEL = 0x02,
    CDC_SUBCLASS_TELEPHONE_CONTROL_MODEL = 0x03,
    CDC_SUBCLASS_MULTICHANNEL_CONTROL_MODEL = 0x04,
    CDC_SUBCLASS_CAPI_CONTROL_MODEL = 0x05,
    CDC_SUBCLASS_ETHERNET_CONTROL_MODEL = 0x06,
    CDC_SUBCLASS_ATM_NETWORKING_CONTROL_MODEL = 0x07,
    CDC_SUBCLASS_WIRELESS_HANDSET_CONTROL_MODEL = 0x08,
    CDC_SUBCLASS_DEVICE_MANAGEMENT = 0x09,
    CDC_SUBCLASS_MOBILE_DIRECT_LINE_MODEL = 0x0A,
    CDC_SUBCLASS_OBEX = 0x0B,
    CDC_SUBCLASS_ETHERNET_EMULATION_MODEL = 0x0C,
    CDC_SUBCLASS_NETWORK_CONTROL_MODEL = 0x0D,
} cdc_subclass_t;

typedef enum
{
    CDC_PROTOCOL_NONE = 0x00,
    CDC_PROTOCOL_ATCOMMAND = 0x01,
    CDC_PROTOCOL_ATCOMMAND_PCCA_101 = 0x02,
    CDC_PROTOCOL_ATCOMMAND_PCCA_101_AND_ANNEXO = 0x03,
    CDC_PROTOCOL_ATCOMMAND_GSM_707 = 0x04,
    CDC_PROTOCOL_ATCOMMAND_3GPP_27007 = 0x05,
    CDC_PROTOCOL_ATCOMMAND_CDMA = 0x06,
    CDC_PROTOCOL_ETHERNET_EMULATION_MODEL = 0x07,
} cdc_protocol_t;

typedef enum
{
    CDC_DESC_HEADER = 0x00,
    CDC_DESC_CALL_MANAGEMENT = 0x01,
    CDC_DESC_ABSTRACT_CONTROL_MANAGEMENT = 0x02,
    CDC_DESC_DIRECT_LINE_MANAGEMENT = 0x03,
    CDC_DESC_TELEPHONE_RINGER = 0x04,
    CDC_DESC_TELEPHONE_CALL_AND_LINE_STATE_REPORTING_CAPACITY = 0x05,
    CDC_DESC_UNION = 0x06,
    CDC_DESC_COUNTRY_SELECTION = 0x07,
    CDC_DESC_TELEPHONE_OPERATIONAL_MODES = 0x08,
    CDC_DESC_USB_TERMINAL = 0x09,
    CDC_DESC_NETWORK_CHANNEL_TERMINAL = 0x0A,
    CDC_DESC_PROTOCOL_UNIT = 0x0B,
    CDC_DESC_EXTENSION_UNIT = 0x0C,
    CDC_DESC_MULTICHANNEL_MANAGEMENT = 0x0D,
    CDC_DESC_CAPI_CONTROL_MANAGEMENT = 0x0E,
    CDC_DESC_ETHERNET_NETWORKING = 0x0F,
    CDC_DESC_ATM_NETWORKING = 0x10,
    CDC_DESC_WIRELESS_HANDSET_CONTROL_MODEL = 0x11,
    CDC_DESC_MOBILE_DIRECT_LINE_MODEL = 0x12,
    CDC_DESC_MOBILE_DIRECT_LINE_MODEL_DETAIL = 0x13,
    CDC_DESC_DEVICE_MANAGEMENT_MODEL = 0x14,
    CDC_DESC_OBEX = 0x15,
    CDC_DESC_COMMAND_SET = 0x16,
    CDC_DESC_COMMAND_SET_DETAIL = 0x17,
    CDC_DESC_TELEPHONE_CONTROL_MODEL = 0x18,
    CDC_DESC_OBEX_SERVICE_IDENTIFIER = 0x19,
    CDC_DESC_NCM = 0x1A,
} cdc_desc_t;

typedef enum
{
    CDC_REQ_SEND_ENCAPSULATED_COMMAND = 0x00,
    CDC_REQ_GET_ENCAPSULATED_RESPONSE = 0x01,
    CDC_REQ_SET_COMM_FEATURE = 0x02,
    CDC_REQ_GET_COMM_FEATURE = 0x03,
    CDC_REQ_CLEAR_COMM_FEATURE = 0x04,

    CDC_REQ_SET_AUX_LINE_STATE = 0x10,
    CDC_REQ_SET_HOOK_STATE = 0x11,
    CDC_REQ_PULSE_SETUP = 0x12,
    CDC_REQ_SEND_PULSE = 0x13,
    CDC_REQ_SET_PULSE_TIME = 0x14,
    CDC_REQ_RING_AUX_JACK = 0x15,

    CDC_REQ_SET_LINE_CODING = 0x20,
    CDC_REQ_GET_LINE_CODING = 0x21,
    CDC_REQ_SET_CONTROL_LINE_STATE = 0x22,
    CDC_REQ_SEND_BREAK = 0x23,

    CDC_REQ_SET_RINGER_PARMS = 0x30,
    CDC_REQ_GET_RINGER_PARMS = 0x31,
    CDC_REQ_SET_OPERATION_PARMS = 0x32,
    CDC_REQ_GET_OPERATION_PARMS = 0x33,
    CDC_REQ_SET_LINE_PARMS = 0x34,
    CDC_REQ_GET_LINE_PARMS = 0x35,
    CDC_REQ_DIAL_DIGITS = 0x36,
    CDC_REQ_SET_UNIT_PARAMETER = 0x37,
    CDC_REQ_GET_UNIT_PARAMETER = 0x38,
    CDC_REQ_CLEAR_UNIT_PARAMETER = 0x39,
    CDC_REQ_GET_PROFILE = 0x3A,

    CDC_REQ_SET_ETHERNET_MULTICAST_FILTERS = 0x40,
    CDC_REQ_SET_ETHERNET_POWER_MANAGEMENT_PATTERN_FILTER = 0x41,
    CDC_REQ_GET_ETHERNET_POWER_MANAGEMENT_PATTERN_FILTER = 0x42,
    CDC_REQ_SET_ETHERNET_PACKET_FILTER = 0x43,
    CDC_REQ_GET_ETHERNET_STATISTIC = 0x44,

    CDC_REQ_SET_ATM_DATA_FORMAT = 0x50,
    CDC_REQ_GET_ATM_DEVICE_STATISTICS = 0x51,
    CDC_REQ_SET_ATM_DEFAULT_VC = 0x52,
    CDC_REQ_GET_ATM_VC_STATISTICS = 0x53,

    CDC_REQ_MDLM_SEMANTIC_MODEL = 0x60,
} cdc_request_t;

/* @struct */
typedef struct __attribute__((packed))
{
    uint32_t bit_rate;
    uint8_t stop_bits;
    uint8_t parity;
    uint8_t data_bits;
} cdc_line_coding_t;

#ifdef __cplusplus
}
#endif

#endif // CDC_H
