/**
 * @file hid.h
 * @author Links (lhd@wch.cn)
 * @brief USB HID class definition header file
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef HID_H
#define HID_H

/* @include */
#include "usb_define.h"

#ifdef __cplusplus
extern "C" {
#endif

/* @enum */
typedef enum
{
    HID_DESC_HID = 0x21,
    HID_DESC_REPORT = 0x22,
    HID_DESC_PHYSICAL = 0x23,
} hid_desc_type_t;

typedef enum
{
    HID_REPORT_TYPE_INPUT = 0x01,
    HID_REPORT_TYPE_OUTPUT = 0x02,
    HID_REPORT_TYPE_FEATURE = 0x03,
} hid_report_type_t;

typedef enum
{
    HID_PROTOCOL_BOOT = 0,
    HID_PROTOCOL_REPORT = 1,
} hid_protocol_t;

typedef enum
{
    HID_CLASS_REQ_GET_REPORT = 0x01,
    HID_CLASS_REQ_GET_IDLE = 0x02,
    HID_CLASS_REQ_GET_PROTOCOL = 0x03,
    HID_CLASS_REQ_SET_REPORT = 0x09,
    HID_CLASS_REQ_SET_IDLE = 0x0A,
    HID_CLASS_REQ_SET_PROTOCOL = 0x0B,
} hid_class_request_t;

typedef enum
{
    HID_KEY_CODE_NONE = 0x00,
    HID_KEY_CODE_A = 0x04,
    HID_KEY_CODE_B = 0x05,
    HID_KEY_CODE_C = 0x06,
    HID_KEY_CODE_D = 0x07,
    HID_KEY_CODE_E = 0x08,
    HID_KEY_CODE_F = 0x09,
    HID_KEY_CODE_G = 0x0A,
    HID_KEY_CODE_H = 0x0B,
    HID_KEY_CODE_I = 0x0C,
    HID_KEY_CODE_J = 0x0D,
    HID_KEY_CODE_K = 0x0E,
    HID_KEY_CODE_L = 0x0F,
    HID_KEY_CODE_M = 0x10,
    HID_KEY_CODE_N = 0x11,
    HID_KEY_CODE_O = 0x12,
    HID_KEY_CODE_P = 0x13,
    HID_KEY_CODE_Q = 0x14,
    HID_KEY_CODE_R = 0x15,
    HID_KEY_CODE_S = 0x16,
    HID_KEY_CODE_T = 0x17,
    HID_KEY_CODE_U = 0x18,
    HID_KEY_CODE_V = 0x19,
    HID_KEY_CODE_W = 0x1A,
    HID_KEY_CODE_X = 0x1B,
    HID_KEY_CODE_Y = 0x1C,
    HID_KEY_CODE_Z = 0x1D,
    HID_KEY_CODE_1 = 0x1E,
    HID_KEY_CODE_2 = 0x1F,
    HID_KEY_CODE_3 = 0x20,
    HID_KEY_CODE_4 = 0x21,
    HID_KEY_CODE_5 = 0x22,
    HID_KEY_CODE_6 = 0x23,
    HID_KEY_CODE_7 = 0x24,
    HID_KEY_CODE_8 = 0x25,
    HID_KEY_CODE_9 = 0x26,
    HID_KEY_CODE_0 = 0x27,
    HID_KEY_CODE_ENTER = 0x28,
    HID_KEY_CODE_ESCAPE = 0x29,
    HID_KEY_CODE_BACKSPACE = 0x2A,
    HID_KEY_CODE_TAB = 0x2B,
    HID_KEY_CODE_SPACE = 0x2C,
    HID_KEY_CODE_MINUS = 0x2D,
    HID_KEY_CODE_EQUAL = 0x2E,
    HID_KEY_CODE_BRACKET_LEFT = 0x2F,
    HID_KEY_CODE_BRACKET_RIGHT = 0x30,
    HID_KEY_CODE_BACKSLASH = 0x31,
    HID_KEY_CODE_EUROPE_1 = 0x32,
    HID_KEY_CODE_SEMICOLON = 0x33,
    HID_KEY_CODE_APOSTROPHE = 0x34,
    HID_KEY_CODE_GRAVE = 0x35,
    HID_KEY_CODE_COMMA = 0x36,
    HID_KEY_CODE_PERIOD = 0x37,
    HID_KEY_CODE_SLASH = 0x38,
    HID_KEY_CODE_CAPS_LOCK = 0x39,
    HID_KEY_CODE_F1 = 0x3A,
    HID_KEY_CODE_F2 = 0x3B,
    HID_KEY_CODE_F3 = 0x3C,
    HID_KEY_CODE_F4 = 0x3D,
    HID_KEY_CODE_F5 = 0x3E,
    HID_KEY_CODE_F6 = 0x3F,
    HID_KEY_CODE_F7 = 0x40,
    HID_KEY_CODE_F8 = 0x41,
    HID_KEY_CODE_F9 = 0x42,
    HID_KEY_CODE_F10 = 0x43,
    HID_KEY_CODE_F11 = 0x44,
    HID_KEY_CODE_F12 = 0x45,
    HID_KEY_CODE_PRINT_SCREEN = 0x46,
    HID_KEY_CODE_SCROLL_LOCK = 0x47,
    HID_KEY_CODE_PAUSE = 0x48,
    HID_KEY_CODE_INSERT = 0x49,
    HID_KEY_CODE_HOME = 0x4A,
    HID_KEY_CODE_PAGE_UP = 0x4B,
    HID_KEY_CODE_DELETE = 0x4C,
    HID_KEY_CODE_END = 0x4D,
    HID_KEY_CODE_PAGE_DOWN = 0x4E,
    HID_KEY_CODE_ARROW_RIGHT = 0x4F,
    HID_KEY_CODE_ARROW_LEFT = 0x50,
    HID_KEY_CODE_ARROW_DOWN = 0x51,
    HID_KEY_CODE_ARROW_UP = 0x52,
    HID_KEY_CODE_NUM_LOCK = 0x53,
    HID_KEY_CODE_KEYPAD_DIVIDE = 0x54,
    HID_KEY_CODE_KEYPAD_MULTIPLY = 0x55,
    HID_KEY_CODE_KEYPAD_SUBTRACT = 0x56,
    HID_KEY_CODE_KEYPAD_ADD = 0x57,
    HID_KEY_CODE_KEYPAD_ENTER = 0x58,
    HID_KEY_CODE_KEYPAD_1 = 0x59,
    HID_KEY_CODE_KEYPAD_2 = 0x5A,
    HID_KEY_CODE_KEYPAD_3 = 0x5B,
    HID_KEY_CODE_KEYPAD_4 = 0x5C,
    HID_KEY_CODE_KEYPAD_5 = 0x5D,
    HID_KEY_CODE_KEYPAD_6 = 0x5E,
    HID_KEY_CODE_KEYPAD_7 = 0x5F,
    HID_KEY_CODE_KEYPAD_8 = 0x60,
    HID_KEY_CODE_KEYPAD_9 = 0x61,
    HID_KEY_CODE_KEYPAD_0 = 0x62,
    HID_KEY_CODE_KEYPAD_DECIMAL = 0x63,
    HID_KEY_CODE_EUROPE_2 = 0x64,
    HID_KEY_CODE_APPLICATION = 0x65,
    HID_KEY_CODE_POWER = 0x66,
    HID_KEY_CODE_KEYPAD_EQUAL = 0x67,
    HID_KEY_CODE_F13 = 0x68,
    HID_KEY_CODE_F14 = 0x69,
    HID_KEY_CODE_F15 = 0x6A,
    HID_KEY_CODE_F16 = 0x6B,
    HID_KEY_CODE_F17 = 0x6C,
    HID_KEY_CODE_F18 = 0x6D,
    HID_KEY_CODE_F19 = 0x6E,
    HID_KEY_CODE_F20 = 0x6F,
    HID_KEY_CODE_F21 = 0x70,
    HID_KEY_CODE_F22 = 0x71,
    HID_KEY_CODE_F23 = 0x72,
    HID_KEY_CODE_F24 = 0x73,
    HID_KEY_CODE_EXECUTE = 0x74,
    HID_KEY_CODE_HELP = 0x75,
    HID_KEY_CODE_MENU = 0x76,
    HID_KEY_CODE_SELECT = 0x77,
    HID_KEY_CODE_STOP = 0x78,
    HID_KEY_CODE_AGAIN = 0x79,
    HID_KEY_CODE_UNDO = 0x7A,
    HID_KEY_CODE_CUT = 0x7B,
    HID_KEY_CODE_COPY = 0x7C,
    HID_KEY_CODE_PASTE = 0x7D,
    HID_KEY_CODE_FIND = 0x7E,
    HID_KEY_CODE_MUTE = 0x7F,
    HID_KEY_CODE_VOLUME_UP = 0x80,
    HID_KEY_CODE_VOLUME_DOWN = 0x81,
    HID_KEY_CODE_LOCKING_CAPS_LOCK = 0x82,
    HID_KEY_CODE_LOCKING_NUM_LOCK = 0x83,
    HID_KEY_CODE_LOCKING_SCROLL_LOCK = 0x84,
    HID_KEY_CODE_KEYPAD_COMMA = 0x85,
    HID_KEY_CODE_KEYPAD_EQUAL_SIGN = 0x86,
    HID_KEY_CODE_KANJI1 = 0x87,
    HID_KEY_CODE_KANJI2 = 0x88,
    HID_KEY_CODE_KANJI3 = 0x89,
    HID_KEY_CODE_KANJI4 = 0x8A,
    HID_KEY_CODE_KANJI5 = 0x8B,
    HID_KEY_CODE_KANJI6 = 0x8C,
    HID_KEY_CODE_KANJI7 = 0x8D,
    HID_KEY_CODE_KANJI8 = 0x8E,
    HID_KEY_CODE_KANJI9 = 0x8F,
    HID_KEY_CODE_LANG1 = 0x90,
    HID_KEY_CODE_LANG2 = 0x91,
    HID_KEY_CODE_LANG3 = 0x92,
    HID_KEY_CODE_LANG4 = 0x93,
    HID_KEY_CODE_LANG5 = 0x94,
    HID_KEY_CODE_LANG6 = 0x95,
    HID_KEY_CODE_LANG7 = 0x96,
    HID_KEY_CODE_LANG8 = 0x97,
    HID_KEY_CODE_LANG9 = 0x98,
    HID_KEY_CODE_ALTERNATE_ERASE = 0x99,
    HID_KEY_CODE_SYSREQ_ATTENTION = 0x9A,
    HID_KEY_CODE_CANCEL = 0x9B,
    HID_KEY_CODE_CLEAR = 0x9C,
    HID_KEY_CODE_PRIOR = 0x9D,
    HID_KEY_CODE_RETURN = 0x9E,
    HID_KEY_CODE_SEPARATOR = 0x9F,
    HID_KEY_CODE_OUT = 0xA0,
    HID_KEY_CODE_OPER = 0xA1,
    HID_KEY_CODE_CLEAR_AGAIN = 0xA2,
    HID_KEY_CODE_CRSEL_PROPS = 0xA3,
    HID_KEY_CODE_EXSEL = 0xA4,

    HID_KEY_CODE_KEYPAD_00 = 0xB0,
    HID_KEY_CODE_KEYPAD_000 = 0xB1,
    HID_KEY_CODE_THOUSANDS_SEPARATOR = 0xB2,
    HID_KEY_CODE_DECIMAL_SEPARATOR = 0xB3,
    HID_KEY_CODE_CURRENCY_UNIT = 0xB4,
    HID_KEY_CODE_CURRENCY_SUBUNIT = 0xB5,
    HID_KEY_CODE_KEYPAD_LEFT_PARENTHESIS = 0xB6,
    HID_KEY_CODE_KEYPAD_RIGHT_PARENTHESIS = 0xB7,
    HID_KEY_CODE_KEYPAD_LEFT_BRACE = 0xB8,
    HID_KEY_CODE_KEYPAD_RIGHT_BRACE = 0xB9,
    HID_KEY_CODE_KEYPAD_TAB = 0xBA,
    HID_KEY_CODE_KEYPAD_BACKSPACE = 0xBB,
    HID_KEY_CODE_KEYPAD_A = 0xBC,
    HID_KEY_CODE_KEYPAD_B = 0xBD,
    HID_KEY_CODE_KEYPAD_C = 0xBE,
    HID_KEY_CODE_KEYPAD_D = 0xBF,
    HID_KEY_CODE_KEYPAD_E = 0xC0,
    HID_KEY_CODE_KEYPAD_F = 0xC1,
    HID_KEY_CODE_KEYPAD_XOR = 0xC2,
    HID_KEY_CODE_KEYPAD_CARET = 0xC3,
    HID_KEY_CODE_KEYPAD_PERCENT = 0xC4,
    HID_KEY_CODE_KEYPAD_LESS_THAN = 0xC5,
    HID_KEY_CODE_KEYPAD_GREATER_THAN = 0xC6,
    HID_KEY_CODE_KEYPAD_AMPERSAND = 0xC7,
    HID_KEY_CODE_KEYPAD_DOUBLE_AMPERSAND = 0xC8,
    HID_KEY_CODE_KEYPAD_VERTICAL_BAR = 0xC9,
    HID_KEY_CODE_KEYPAD_DOUBLE_VERTICAL_BAR = 0xCA,
    HID_KEY_CODE_KEYPAD_COLON = 0xCB,
    HID_KEY_CODE_KEYPAD_HASH = 0xCC,
    HID_KEY_CODE_KEYPAD_SPACE = 0xCD,
    HID_KEY_CODE_KEYPAD_AT = 0xCE,
    HID_KEY_CODE_KEYPAD_EXCLAMATION = 0xCF,
    HID_KEY_CODE_KEYPAD_MEMORY_STORE = 0xD0,
    HID_KEY_CODE_KEYPAD_MEMORY_RECALL = 0xD1,
    HID_KEY_CODE_KEYPAD_MEMORY_CLEAR = 0xD2,
    HID_KEY_CODE_KEYPAD_MEMORY_ADD = 0xD3,
    HID_KEY_CODE_KEYPAD_MEMORY_SUBTRACT = 0xD4,
    HID_KEY_CODE_KEYPAD_MEMORY_MULTIPLY = 0xD5,
    HID_KEY_CODE_KEYPAD_MEMORY_DIVIDE = 0xD6,
    HID_KEY_CODE_KEYPAD_PLUS_MINUS = 0xD7,
    HID_KEY_CODE_KEYPAD_CLEAR = 0xD8,
    HID_KEY_CODE_KEYPAD_CLEAR_ENTRY = 0xD9,
    HID_KEY_CODE_KEYPAD_BINARY = 0xDA,
    HID_KEY_CODE_KEYPAD_OCTAL = 0xDB,
    HID_KEY_CODE_KEYPAD_DECIMAL_2 = 0xDC,
    HID_KEY_CODE_KEYPAD_HEXADECIMAL = 0xDD,

    HID_KEY_CODE_CONTROL_LEFT = 0xE0,
    HID_KEY_CODE_SHIFT_LEFT = 0xE1,
    HID_KEY_CODE_ALT_LEFT = 0xE2,
    HID_KEY_CODE_GUI_LEFT = 0xE3,
    HID_KEY_CODE_CONTROL_RIGHT = 0xE4,
    HID_KEY_CODE_SHIFT_RIGHT = 0xE5,
    HID_KEY_CODE_ALT_RIGHT = 0xE6,
    HID_KEY_CODE_GUI_RIGHT = 0xE7,
} hid_key_code_t;

/* @struct */
typedef struct __attribute__((packed))
{
    uint8_t bLength;
    uint8_t bDescriptorType;
    uint16_t bcdHID;
    uint8_t bCountryCode;
    uint8_t bNumDescriptors;
    uint8_t bReportType;
    uint16_t wReportLength;
} hid_desc_t;

#ifdef __cplusplus
}
#endif

#endif // HID_H
