########################################
# Makefile for CDC-ACM Example
########################################

# --- Supported chips ---
SUPPORTED_CHIPS := \
	ch32v407ret6 \
	ch32v407vet6 \
	ch32v407weu6 \
	ch32v467ret6 \
	ch32v467vet6 \
	ch32v467weu6 \
	ch32v303cbt6 \
	ch32v303rbt6 \
	ch32v303rct6 \
	ch32v303rct7 \
	ch32v303vct6 \
	ch32v305cct6 \
	ch32v305fbp6 \
	ch32v305gbu6 \
	ch32v305rbt6 \
	ch32v307rct6 \
	ch32v307vct6 \
	ch32v307wcu6 \
	ch32v317vct6 \
	ch32v317wcu6 \
	ch32v205cct6 \
	ch32v205rct6 \
	ch32v205vct6 \
	ch32v203cct6

# --- Include Host Examples Makefile ---
include ../host.mk
