########################################
# Makefile for HID KM Example
########################################

# --- Root Directory ---
ROOT_DIR := $(abspath ../../../)

# --- Supported Families ---
SUPPORTED_FAMILIES := ch32v205

# --- Include Device Examples Makefile ---
include $(ROOT_DIR)/examples/device/device.mk
