########################################
# Makefile for HID KM Example
########################################

# --- Supported chips ---
SUPPORTED_CHIPS := \
	ch32v205cct6 \
	ch32v205rct6 \
	ch32v205vct6 \
	ch32v203cct6

# --- Include Device Examples Makefile ---
include ../device.mk
