########################################
# Makefile for CDC-ACM Bridge Example
########################################

# --- Supported chips ---
SUPPORTED_CHIPS := \
	ch32v407vet6 \
	ch32v407weu6 \
	ch32v467vet6 \
	ch32v467weu6 \
	ch32v205cct6 \
	ch32v205rct6 \
	ch32v205vct6

# --- Include Dual Device Examples Makefile ---
include ../dual_device.mk
